package co.edu.eam.modelo;
// Generated 12/09/2016 01:19:13 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name="periodo"
    ,schema="public"
)
public class Periodo  implements java.io.Serializable {


     private Integer id;
     private Integer anio;
     private Integer periodo;
     private String nombre;
     private Set<Evaluacion> evaluacions = new HashSet<Evaluacion>(0);
     private Set<Pregunta> preguntas = new HashSet<Pregunta>(0);

    public Periodo() {
    }

	
    public Periodo(Integer id, Integer anio, Integer periodo, String nombre) {
        this.id = id;
        this.anio = anio;
        this.periodo = periodo;
        this.nombre = nombre;
    }
    public Periodo(Integer id, Integer anio, Integer periodo, String nombre, Set<Evaluacion> evaluacions, Set<Pregunta> preguntas) {
       this.id = id;
       this.anio = anio;
       this.periodo = periodo;
       this.nombre = nombre;
       this.evaluacions = evaluacions;
       this.preguntas = preguntas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="anio", nullable=false)
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    
    @Column(name="periodo", nullable=false)
    public Integer getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodo")
    public Set<Evaluacion> getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set<Evaluacion> evaluacions) {
        this.evaluacions = evaluacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodo")
    public Set<Pregunta> getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set<Pregunta> preguntas) {
        this.preguntas = preguntas;
    }




}


