package co.edu.eam.modelo;
// Generated 12/09/2016 01:19:13 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pregunta generated by hbm2java
 */
@Entity
@Table(name="pregunta"
    ,schema="public"
)
public class Pregunta  implements java.io.Serializable {


     private Integer id;
     private Periodo periodo;
     private TipoEvaluacion tipoEvaluacion;
     private String pregunta;
     private String estado;
     private Set<Respuesta> respuestas = new HashSet<Respuesta>(0);

    public Pregunta() {
    }

	
    public Pregunta(Integer id, Periodo periodo, TipoEvaluacion tipoEvaluacion, String pregunta, String estado) {
        this.id = id;
        this.periodo = periodo;
        this.tipoEvaluacion = tipoEvaluacion;
        this.pregunta = pregunta;
        this.estado = estado;
    }
    public Pregunta(Integer id, Periodo periodo, TipoEvaluacion tipoEvaluacion, String pregunta, String estado, Set<Respuesta> respuestas) {
       this.id = id;
       this.periodo = periodo;
       this.tipoEvaluacion = tipoEvaluacion;
       this.pregunta = pregunta;
       this.estado = estado;
       this.respuestas = respuestas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="periodo_id", nullable=false)
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_evaluacion_id", nullable=false)
    public TipoEvaluacion getTipoEvaluacion() {
        return this.tipoEvaluacion;
    }
    
    public void setTipoEvaluacion(TipoEvaluacion tipoEvaluacion) {
        this.tipoEvaluacion = tipoEvaluacion;
    }

    
    @Column(name="pregunta", nullable=false, length=30)
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pregunta")
    public Set<Respuesta> getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set<Respuesta> respuestas) {
        this.respuestas = respuestas;
    }




}


