package co.edu.eam.modelo;
// Generated 12/09/2016 01:19:13 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Presentacion generated by hbm2java
 */
@Entity
@Table(name="presentacion"
    ,schema="public"
)
public class Presentacion  implements java.io.Serializable {


     private Integer id;
     private Evaluacion evaluacion;
     private String evaluador;
     private String docente;
     private String comentario;
     private String materia;
     private String estado;
     private Set<Respuesta> respuestas = new HashSet<Respuesta>(0);

    public Presentacion() {
    }

	
    public Presentacion(Integer id, Evaluacion evaluacion, String evaluador, String docente, String comentario, String estado) {
        this.id = id;
        this.evaluacion = evaluacion;
        this.evaluador = evaluador;
        this.docente = docente;
        this.comentario = comentario;
        this.estado = estado;
    }
    public Presentacion(Integer id, Evaluacion evaluacion, String evaluador, String docente, String comentario, String materia, String estado, Set<Respuesta> respuestas) {
       this.id = id;
       this.evaluacion = evaluacion;
       this.evaluador = evaluador;
       this.docente = docente;
       this.comentario = comentario;
       this.materia = materia;
       this.estado = estado;
       this.respuestas = respuestas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evaluacion_id", nullable=false)
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }

    
    @Column(name="evaluador", nullable=false, length=30)
    public String getEvaluador() {
        return this.evaluador;
    }
    
    public void setEvaluador(String evaluador) {
        this.evaluador = evaluador;
    }

    
    @Column(name="docente", nullable=false, length=30)
    public String getDocente() {
        return this.docente;
    }
    
    public void setDocente(String docente) {
        this.docente = docente;
    }

    
    @Column(name="comentario", nullable=false, length=300)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="materia", length=30)
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="presentacion")
    public Set<Respuesta> getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set<Respuesta> respuestas) {
        this.respuestas = respuestas;
    }




}


