package co.edu.eam.modelo;
// Generated 12/09/2016 01:19:13 AM by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Respuesta generated by hbm2java
 */
@Entity
@Table(name="respuesta"
    ,schema="public"
)
public class Respuesta  implements java.io.Serializable {


     private Integer id;
     private Pregunta pregunta;
     private Presentacion presentacion;
     private Integer nota;

    public Respuesta() {
    }

    public Respuesta(Integer id, Pregunta pregunta, Presentacion presentacion, Integer nota) {
       this.id = id;
       this.pregunta = pregunta;
       this.presentacion = presentacion;
       this.nota = nota;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pregunta_id", nullable=false)
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="presentacion_id", nullable=false)
    public Presentacion getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(Presentacion presentacion) {
        this.presentacion = presentacion;
    }

    
    @Column(name="nota", nullable=false)
    public Integer getNota() {
        return this.nota;
    }
    
    public void setNota(Integer nota) {
        this.nota = nota;
    }




}


